(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z"
"Otherwise," "Otherwise:" "__FILE__" "__LINE__" "__PACKAGE__" "__SUB__"
"abs" "accept" "alarm" "atan2" "bind" "binmode" "bless" "break" "caller"
"chdir" "chmod" "chomp" "chop" "chown" "chr" "chroot" "close" "closedir"
"connect" "continue" "cos" "crypt" "dbmclose" "dbmopen" "defined" "delete"
"die" "do" "dump" "each" "endgrent" "endhostent" "endnetent" "endprotoent"
"endpwent" "endservent" "eof" "eval" "evalbytes" "exec" "exists" "exit"
"exp" "fc" "fcntl" "fileno" "flock" "fork" "format" "formline" "getc"
"getgrent" "getgrgid" "getgrnam" "gethostbyaddr" "gethostbyname"
"gethostent" "getlogin" "getnetbyaddr" "getnetbyname" "getnetent"
"getpeername" "getpgrp" "getppid" "getpriority" "getprotobyname"
"getprotobynumber" "getprotoent" "getpwent" "getpwnam" "getpwuid"
"getservbyname" "getservbyport" "getservent" "getsockname" "getsockopt"
"glob" "gmtime" "goto" "grep" "hex" "import" "index" "int" "ioctl" "join"
"keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen" "local"
"localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl" "msgget"
"msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord" "our"
"pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype" "push" "q"
"qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir" "readline"
"readlink" "readpipe" "recv" "redo" "ref" "rename" "require" "reset"
"return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say" "scalar" "seek"
"seekdir" "select" "semctl" "semget" "semop" "send" "setgrent" "sethostent"
"setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent" "setservent"
"setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite" "shutdown"
"sin" "sleep" "socket" "socketpair" "sort" "splice" "split" "sprintf"
"sqrt" "srand" "stat" "state" "study" "sub" "substr" "symlink" "syscall"
"sysopen" "sysread" "sysseek" "system" "syswrite" "tell" "telldir" "tie"
"tied" "time" "times" "tr" "truncate" "uc" "ucfirst" "umask" "undef"
"unlink" "unpack" "unshift" "untie" "use" "utime" "values" "vec" "wait"
"waitpid" "wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"Algorithm::Diff" "Algorithm::DiffOld" "AnyDBM_File" "App::Cpan"
"App::Prove" "App::Prove::State" "App::Prove::State::Result"
"App::Prove::State::Result::Test" "App::cpanminus"
"App::cpanminus::fatscript" "Archive::Zip" "Archive::Zip::Archive"
"Archive::Zip::BufferedFileHandle" "Archive::Zip::DirectoryMember"
"Archive::Zip::FAQ" "Archive::Zip::FileMember" "Archive::Zip::Member"
"Archive::Zip::MemberRead" "Archive::Zip::MockFileHandle"
"Archive::Zip::NewFileMember" "Archive::Zip::StringMember"
"Archive::Zip::Tree" "Archive::Zip::ZipFileMember" "Attribute::Handlers"
"AutoLoader" "AutoSplit" "B" "B::Concise" "B::Debug" "B::Deparse"
"B::Showlex" "B::Terse" "B::Xref" "Benchmark" "Business::ISBN"
"Business::ISBN10" "Business::ISBN13" "Business::ISBN::Data" "CORE" "CPAN"
"CPAN::API::HOWTO" "CPAN::Author" "CPAN::Bundle" "CPAN::CacheMgr"
"CPAN::Complete" "CPAN::Debug" "CPAN::DeferredCode" "CPAN::Distribution"
"CPAN::Distroprefs" "CPAN::Distrostatus"
"CPAN::Exception::RecursiveDependency" "CPAN::Exception::blocked_urllist"
"CPAN::Exception::yaml_not_installed" "CPAN::Exception::yaml_process_error"
"CPAN::FTP" "CPAN::FTP::netrc" "CPAN::FirstTime" "CPAN::HTTP::Client"
"CPAN::HTTP::Credentials" "CPAN::HandleConfig" "CPAN::Index"
"CPAN::InfoObj" "CPAN::Kwalify" "CPAN::LWP::UserAgent" "CPAN::Meta"
"CPAN::Meta::Converter" "CPAN::Meta::Feature" "CPAN::Meta::History"
"CPAN::Meta::History::Meta_1_0" "CPAN::Meta::History::Meta_1_1"
"CPAN::Meta::History::Meta_1_2" "CPAN::Meta::History::Meta_1_3"
"CPAN::Meta::History::Meta_1_4" "CPAN::Meta::Merge" "CPAN::Meta::Prereqs"
"CPAN::Meta::Requirements" "CPAN::Meta::Spec" "CPAN::Meta::Validator"
"CPAN::Meta::YAML" "CPAN::Mirrors" "CPAN::Module" "CPAN::Nox"
"CPAN::Prompt" "CPAN::Queue" "CPAN::Shell" "CPAN::Tarzip" "CPAN::URL"
"CPAN::Version" "Cache::BaseCache" "Cache::BaseCacheTester" "Cache::Cache"
"Cache::CacheMetaData" "Cache::CacheSizer" "Cache::CacheTester"
"Cache::CacheUtils" "Cache::FileBackend" "Cache::FileCache"
"Cache::MemoryBackend" "Cache::MemoryCache" "Cache::NullCache"
"Cache::Object" "Cache::SharedMemoryBackend" "Cache::SharedMemoryCache"
"Cache::SizeAwareCache" "Cache::SizeAwareCacheTester"
"Cache::SizeAwareFileCache" "Cache::SizeAwareMemoryCache"
"Cache::SizeAwareSharedMemoryCache" "Carp" "Carp::Heavy" "Carton"
"Carton::Builder" "Carton::CLI" "Carton::CPANfile" "Carton::Dependency"
"Carton::Dist" "Carton::Dist::Core" "Carton::Doc::Bundle"
"Carton::Doc::Check" "Carton::Doc::Exec" "Carton::Doc::FAQ"
"Carton::Doc::Fatpack" "Carton::Doc::Install" "Carton::Doc::List"
"Carton::Doc::Show" "Carton::Doc::Tree" "Carton::Doc::Update"
"Carton::Doc::Upgrading" "Carton::Doc::Version" "Carton::Environment"
"Carton::Error" "Carton::Index" "Carton::Mirror" "Carton::Package"
"Carton::Packer" "Carton::Snapshot" "Carton::Snapshot::Emitter"
"Carton::Snapshot::Parser" "Carton::Tree" "Carton::Util" "Class::Inspector"
"Class::Inspector::Functions" "Class::Std" "Class::Std::Storable"
"Class::Struct" "Class::Tiny" "Clone" "Compress::Raw::Bzip2"
"Compress::Raw::Zlib" "Compress::Zlib" "Config" "Config::Extensions"
"Config::Tiny" "Cwd" "DB" "DBM_Filter" "DBM_Filter::compress"
"DBM_Filter::encode" "DBM_Filter::int32" "DBM_Filter::null"
"DBM_Filter::utf8" "Data::Dumper" "Date::Format" "Date::Language"
"Date::Language::Afar" "Date::Language::Amharic" "Date::Language::Austrian"
"Date::Language::Brazilian" "Date::Language::Bulgarian"
"Date::Language::Chinese" "Date::Language::Chinese_GB"
"Date::Language::Czech" "Date::Language::Danish" "Date::Language::Dutch"
"Date::Language::English" "Date::Language::Finnish"
"Date::Language::French" "Date::Language::Gedeo" "Date::Language::German"
"Date::Language::Greek" "Date::Language::Hungarian"
"Date::Language::Icelandic" "Date::Language::Italian"
"Date::Language::Norwegian" "Date::Language::Oromo"
"Date::Language::Romanian" "Date::Language::Russian"
"Date::Language::Russian_cp1251" "Date::Language::Russian_koi8r"
"Date::Language::Sidama" "Date::Language::Somali" "Date::Language::Spanish"
"Date::Language::Swedish" "Date::Language::Tigrinya"
"Date::Language::TigrinyaEritrean" "Date::Language::TigrinyaEthiopian"
"Date::Language::Turkish" "Date::Parse" "Devel::InnerPackage"
"Devel::PPPort" "Devel::Peek" "Devel::SelfStubber" "Digest" "Digest::MD5"
"Digest::SHA" "Digest::SHA1" "Digest::base" "Digest::file" "DirHandle"
"Dumpvalue" "DynaLoader" "Emacs::PDE" "Emacs::PDE::Util" "Encode"
"Encode::Alias" "Encode::Byte" "Encode::CJKConstants" "Encode::CN"
"Encode::CN::HZ" "Encode::Config" "Encode::EBCDIC" "Encode::Encoder"
"Encode::Encoding" "Encode::GSM0338" "Encode::Guess" "Encode::JP"
"Encode::JP::H2Z" "Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR"
"Encode::Locale" "Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP"
"Encode::MIME::Name" "Encode::PerlIO" "Encode::Supported" "Encode::Symbol"
"Encode::TW" "Encode::Unicode" "Encode::Unicode::UTF7" "English" "Errno"
"Error" "Error::Simple" "Exporter" "Exporter::Heavy" "Exporter::Shiny"
"Exporter::Tiny" "ExtUtils::CBuilder" "ExtUtils::CBuilder::Base"
"ExtUtils::CBuilder::Platform::Unix" "ExtUtils::CBuilder::Platform::VMS"
"ExtUtils::CBuilder::Platform::Windows"
"ExtUtils::CBuilder::Platform::Windows::BCC"
"ExtUtils::CBuilder::Platform::Windows::GCC"
"ExtUtils::CBuilder::Platform::Windows::MSVC"
"ExtUtils::CBuilder::Platform::aix" "ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Config"
"ExtUtils::Constant" "ExtUtils::Constant::Base"
"ExtUtils::Constant::ProxySubs" "ExtUtils::Constant::Utils"
"ExtUtils::Constant::XS" "ExtUtils::Helpers" "ExtUtils::Helpers::Unix"
"ExtUtils::Helpers::VMS" "ExtUtils::Helpers::Windows" "ExtUtils::Install"
"ExtUtils::InstallPaths" "ExtUtils::Installed" "ExtUtils::Liblist"
"ExtUtils::Liblist::Kid" "ExtUtils::MM" "ExtUtils::MM_AIX"
"ExtUtils::MM_Any" "ExtUtils::MM_BeOS" "ExtUtils::MM_Cygwin"
"ExtUtils::MM_DOS" "ExtUtils::MM_Darwin" "ExtUtils::MM_MacOS"
"ExtUtils::MM_NW5" "ExtUtils::MM_OS2" "ExtUtils::MM_QNX"
"ExtUtils::MM_UWIN" "ExtUtils::MM_Unix" "ExtUtils::MM_VMS"
"ExtUtils::MM_VOS" "ExtUtils::MM_Win32" "ExtUtils::MM_Win95" "ExtUtils::MY"
"ExtUtils::MakeMaker" "ExtUtils::MakeMaker::Config"
"ExtUtils::MakeMaker::FAQ" "ExtUtils::MakeMaker::Tutorial"
"ExtUtils::Manifest" "ExtUtils::Miniperl" "ExtUtils::Mkbootstrap"
"ExtUtils::Mksymlists" "ExtUtils::Packlist" "ExtUtils::ParseXS"
"ExtUtils::ParseXS::Constants" "ExtUtils::ParseXS::CountLines"
"ExtUtils::ParseXS::Utilities" "ExtUtils::Typemaps"
"ExtUtils::Typemaps::Cmd" "ExtUtils::Typemaps::InputMap"
"ExtUtils::Typemaps::OutputMap" "ExtUtils::Typemaps::Type"
"ExtUtils::testlib" "Fcntl" "File::Basename" "File::Compare" "File::Copy"
"File::DosGlob" "File::Find" "File::Glob" "File::GlobMapper"
"File::Listing" "File::Path" "File::Remove" "File::Spec"
"File::Spec::Cygwin" "File::Spec::Epoc" "File::Spec::Functions"
"File::Spec::Mac" "File::Spec::OS2" "File::Spec::Unix" "File::Spec::Win32"
"File::Temp" "File::stat" "FileCache" "FileHandle" "Filter::Simple"
"Filter::Util::Call" "Filter::Util::Exec" "Filter::Util::perlfilter"
"Filter::cpp" "Filter::decrypt" "Filter::exec" "Filter::sh" "Filter::tee"
"FindBin" "GDBM_File" "Getopt::Long" "Getopt::Std" "Git" "Git::I18N"
"Git::IndexInfo" "HTML::Entities" "HTML::Filter" "HTML::HeadParser"
"HTML::LinkExtor" "HTML::Parser" "HTML::PullParser" "HTML::Tagset"
"HTML::TokeParser" "HTTP::Config" "HTTP::Cookies"
"HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape" "HTTP::Daemon"
"HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth" "HTTP::Headers::ETag"
"HTTP::Headers::Util" "HTTP::Message" "HTTP::Negotiate" "HTTP::Request"
"HTTP::Request::Common" "HTTP::Response" "HTTP::Status" "HTTP::Tiny"
"Hash::Util" "Hash::Util::FieldHash" "Hook::LexWrap" "I18N::Collate"
"I18N::LangTags" "I18N::LangTags::Detect" "I18N::LangTags::List"
"I18N::Langinfo" "IO" "IO::Compress::Adapter::Bzip2"
"IO::Compress::Adapter::Deflate" "IO::Compress::Adapter::Identity"
"IO::Compress::Base" "IO::Compress::Base::Common" "IO::Compress::Bzip2"
"IO::Compress::Deflate" "IO::Compress::FAQ" "IO::Compress::Gzip"
"IO::Compress::Gzip::Constants" "IO::Compress::RawDeflate"
"IO::Compress::Zip" "IO::Compress::Zip::Constants"
"IO::Compress::Zlib::Constants" "IO::Compress::Zlib::Extra" "IO::Dir"
"IO::File" "IO::HTML" "IO::Handle" "IO::Pipe" "IO::Poll" "IO::Seekable"
"IO::Select" "IO::Socket" "IO::Socket::INET" "IO::Socket::IP"
"IO::Socket::SSL" "IO::Socket::SSL::Intercept" "IO::Socket::SSL::Utils"
"IO::Socket::UNIX" "IO::String" "IO::Uncompress::Adapter::Bunzip2"
"IO::Uncompress::Adapter::Identity" "IO::Uncompress::Adapter::Inflate"
"IO::Uncompress::AnyInflate" "IO::Uncompress::AnyUncompress"
"IO::Uncompress::Base" "IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IPC::Cmd" "IPC::Msg" "IPC::Open2" "IPC::Open3"
"IPC::Semaphore" "IPC::SharedMem" "IPC::SysV" "JSON" "JSON::PP"
"JSON::PP::Boolean" "JSON::backportPP" "JSON::backportPP::Boolean"
"JSON::backportPP::Compat5005" "JSON::backportPP::Compat5006" "LWP"
"LWP::Authen::Basic" "LWP::Authen::Digest" "LWP::Authen::Ntlm"
"LWP::ConnCache" "LWP::Debug" "LWP::DebugFile" "LWP::MediaTypes"
"LWP::MemberMixin" "LWP::Protocol" "LWP::Protocol::GHTTP"
"LWP::Protocol::cpan" "LWP::Protocol::data" "LWP::Protocol::file"
"LWP::Protocol::ftp" "LWP::Protocol::gopher" "LWP::Protocol::http"
"LWP::Protocol::loopback" "LWP::Protocol::mailto" "LWP::Protocol::nntp"
"LWP::Protocol::nogo" "LWP::RobotUA" "LWP::Simple" "LWP::UserAgent"
"List::AllUtils" "List::MoreUtils" "List::MoreUtils::Contributing"
"List::MoreUtils::PP" "List::MoreUtils::XS" "List::SomeUtils"
"List::SomeUtils::PP" "List::SomeUtils::XS" "List::Util" "List::Util::XS"
"List::UtilsBy" "Locale::Maketext" "Locale::Maketext::Cookbook"
"Locale::Maketext::Guts" "Locale::Maketext::GutsLoader"
"Locale::Maketext::Simple" "Locale::Maketext::TPJ13" "Log::Handler"
"Log::Handler::Config" "Log::Handler::Examples" "Log::Handler::Levels"
"Log::Handler::Output" "Log::Handler::Output::DBI"
"Log::Handler::Output::Email" "Log::Handler::Output::File"
"Log::Handler::Output::Forward" "Log::Handler::Output::Screen"
"Log::Handler::Output::Sendmail" "Log::Handler::Output::Socket"
"Log::Handler::Pattern" "Log::Handler::Plugin::Config::General"
"Log::Handler::Plugin::Config::Properties" "Log::Handler::Plugin::YAML"
"MIME::Base64" "MIME::QuotedPrint" "Math::BigFloat" "Math::BigFloat::Trace"
"Math::BigInt" "Math::BigInt::Calc" "Math::BigInt::CalcEmu"
"Math::BigInt::FastCalc" "Math::BigInt::Trace" "Math::BigRat"
"Math::Complex" "Math::Trig" "Memoize" "Memoize::AnyDBM_File"
"Memoize::Expire" "Memoize::ExpireFile" "Memoize::ExpireTest"
"Memoize::NDBM_File" "Memoize::SDBM_File" "Memoize::Storable"
"Module::Build" "Module::Build::API" "Module::Build::Authoring"
"Module::Build::Base" "Module::Build::Bundling" "Module::Build::Compat"
"Module::Build::Config" "Module::Build::ConfigData"
"Module::Build::Cookbook" "Module::Build::Dumper"
"Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Tiny" "Module::Build::Version" "Module::Build::YAML"
"Module::CPANfile" "Module::CPANfile::Environment"
"Module::CPANfile::Prereq" "Module::CPANfile::Prereqs"
"Module::CPANfile::Requirement" "Module::CoreList"
"Module::CoreList::TieHashDelta" "Module::Implementation" "Module::Load"
"Module::Load::Conditional" "Module::Metadata" "Module::Pluggable"
"Module::Pluggable::Object" "Module::Reader" "Module::Runtime"
"Module::Signature" "NDBM_File" "NEXT" "Net::Cmd" "Net::Config"
"Net::Domain" "Net::FTP" "Net::FTP::A" "Net::FTP::E" "Net::FTP::I"
"Net::FTP::L" "Net::FTP::dataconn" "Net::HTTP" "Net::HTTP::Methods"
"Net::HTTP::NB" "Net::HTTPS" "Net::LibIDN" "Net::NNTP" "Net::Netrc"
"Net::POP3" "Net::Ping" "Net::SMTP" "Net::SSLeay" "Net::SSLeay::Handle"
"Net::Time" "Net::hostent" "Net::libnetFAQ" "Net::netent" "Net::protoent"
"Net::servent" "O" "ODBM_File" "Opcode" "PAR::Dist" "POD2::DE::local::lib"
"POD2::PT_BR::local::lib" "POSIX" "PPI" "PPI::Cache" "PPI::Document"
"PPI::Document::File" "PPI::Document::Fragment" "PPI::Document::Normalized"
"PPI::Dumper" "PPI::Element" "PPI::Exception"
"PPI::Exception::ParserRejection" "PPI::Exception::ParserTimeout"
"PPI::Find" "PPI::Lexer" "PPI::Node" "PPI::Normal" "PPI::Normal::Standard"
"PPI::Statement" "PPI::Statement::Break" "PPI::Statement::Compound"
"PPI::Statement::Data" "PPI::Statement::End" "PPI::Statement::Expression"
"PPI::Statement::Given" "PPI::Statement::Include"
"PPI::Statement::Include::Perl6" "PPI::Statement::Null"
"PPI::Statement::Package" "PPI::Statement::Scheduled" "PPI::Statement::Sub"
"PPI::Statement::Unknown" "PPI::Statement::UnmatchedBrace"
"PPI::Statement::Variable" "PPI::Statement::When" "PPI::Structure"
"PPI::Structure::Block" "PPI::Structure::Condition"
"PPI::Structure::Constructor" "PPI::Structure::For" "PPI::Structure::Given"
"PPI::Structure::List" "PPI::Structure::Subscript"
"PPI::Structure::Unknown" "PPI::Structure::When" "PPI::Token"
"PPI::Token::ArrayIndex" "PPI::Token::Attribute" "PPI::Token::BOM"
"PPI::Token::Cast" "PPI::Token::Comment" "PPI::Token::DashedWord"
"PPI::Token::Data" "PPI::Token::End" "PPI::Token::HereDoc"
"PPI::Token::Label" "PPI::Token::Magic" "PPI::Token::Number"
"PPI::Token::Number::Binary" "PPI::Token::Number::Exp"
"PPI::Token::Number::Float" "PPI::Token::Number::Hex"
"PPI::Token::Number::Octal" "PPI::Token::Number::Version"
"PPI::Token::Operator" "PPI::Token::Pod" "PPI::Token::Prototype"
"PPI::Token::Quote" "PPI::Token::Quote::Double"
"PPI::Token::Quote::Interpolate" "PPI::Token::Quote::Literal"
"PPI::Token::Quote::Single" "PPI::Token::QuoteLike"
"PPI::Token::QuoteLike::Backtick" "PPI::Token::QuoteLike::Command"
"PPI::Token::QuoteLike::Readline" "PPI::Token::QuoteLike::Regexp"
"PPI::Token::QuoteLike::Words" "PPI::Token::Regexp"
"PPI::Token::Regexp::Match" "PPI::Token::Regexp::Substitute"
"PPI::Token::Regexp::Transliterate" "PPI::Token::Separator"
"PPI::Token::Structure" "PPI::Token::Symbol" "PPI::Token::Unknown"
"PPI::Token::Whitespace" "PPI::Token::Word" "PPI::Token::_QuoteEngine"
"PPI::Token::_QuoteEngine::Full" "PPI::Token::_QuoteEngine::Simple"
"PPI::Tokenizer" "PPI::Transform" "PPI::Transform::UpdateCopyright"
"PPI::Util" "PPI::XSAccessor" "Params::Check" "Params::Util"
"Params::Validate" "Params::Validate::Constants" "Params::Validate::PP"
"Params::Validate::XS" "Params::ValidatePP" "Params::ValidateXS"
"Parse::CPAN::Meta" "Path::Tiny" "Perl::OSType" "PerlIO" "PerlIO::encoding"
"PerlIO::mmap" "PerlIO::scalar" "PerlIO::via" "PerlIO::via::QuotedPrint"
"PlSense" "PlSense::AddressFinder" "PlSense::AddressRouter"
"PlSense::Builtin" "PlSense::Cacheable" "PlSense::CodeAssist"
"PlSense::Configure" "PlSense::Entity" "PlSense::Entity::Array"
"PlSense::Entity::Hash" "PlSense::Entity::Instance" "PlSense::Entity::Null"
"PlSense::Entity::Reference" "PlSense::Entity::Scalar" "PlSense::Helper"
"PlSense::Logger" "PlSense::ModuleBuilder"
"PlSense::ModuleBuilder::DocBuilder"
"PlSense::ModuleBuilder::InheritBuilder"
"PlSense::ModuleBuilder::PPIBuilder"
"PlSense::ModuleBuilder::PPIBuilder::IncludeStmt"
"PlSense::ModuleBuilder::XrefBuilder" "PlSense::ModuleKeeper"
"PlSense::ModuleSrcUpdater" "PlSense::Plugin::AddressFinder"
"PlSense::Plugin::AddressFinder::Builtin"
"PlSense::Plugin::AddressFinder::Builtin::Bless"
"PlSense::Plugin::AddressFinder::Builtin::Eval"
"PlSense::Plugin::AddressFinder::Builtin::First"
"PlSense::Plugin::AddressFinder::Builtin::Grep"
"PlSense::Plugin::AddressFinder::Builtin::Pop"
"PlSense::Plugin::AddressFinder::Builtin::Push"
"PlSense::Plugin::AddressFinder::Builtin::Reverse"
"PlSense::Plugin::AddressFinder::Builtin::Shift"
"PlSense::Plugin::AddressFinder::Builtin::Sort"
"PlSense::Plugin::AddressFinder::Builtin::Undef"
"PlSense::Plugin::AddressFinder::Builtin::Unshift"
"PlSense::Plugin::AddressFinder::Builtin::Values"
"PlSense::Plugin::AddressFinder::Ext"
"PlSense::Plugin::AddressFinder::Ext::First"
"PlSense::Plugin::AddressFinder::Ext::Uniq"
"PlSense::Plugin::CodeAssistant"
"PlSense::Plugin::CodeAssistant::ExplicitMethod"
"PlSense::Plugin::CodeAssistant::HashMember"
"PlSense::Plugin::CodeAssistant::InstanceMethod"
"PlSense::Plugin::CodeAssistant::Method"
"PlSense::Plugin::CodeAssistant::MethodArgument"
"PlSense::Plugin::CodeAssistant::Module"
"PlSense::Plugin::CodeAssistant::StaticMethod"
"PlSense::Plugin::CodeAssistant::Sub"
"PlSense::Plugin::CodeAssistant::UseArgument"
"PlSense::Plugin::CodeAssistant::Variable" "PlSense::Plugin::IncludeStmt"
"PlSense::Plugin::IncludeStmt::Lib" "PlSense::Plugin::IncludeStmt::Vars"
"PlSense::Plugin::PPIBuilder" "PlSense::Plugin::PPIBuilder::ClassStd"
"PlSense::Plugin::PPIBuilder::Default" "PlSense::SocketClient"
"PlSense::SubstituteBuilder" "PlSense::SubstituteKeeper" "PlSense::Symbol"
"PlSense::Symbol::Method" "PlSense::Symbol::Module"
"PlSense::Symbol::Variable" "PlSense::Util" "Pod::Escapes" "Pod::Functions"
"Pod::Html" "Pod::Man" "Pod::ParseLink" "Pod::Perldoc"
"Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO" "Pod::Perldoc::ToANSI"
"Pod::Perldoc::ToChecker" "Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff"
"Pod::Perldoc::ToPod" "Pod::Perldoc::ToRtf" "Pod::Perldoc::ToTerm"
"Pod::Perldoc::ToText" "Pod::Perldoc::ToTk" "Pod::Perldoc::ToXml"
"Pod::Simple" "Pod::Simple::BlackBox" "Pod::Simple::Checker"
"Pod::Simple::Debug" "Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML"
"Pod::Simple::HTML" "Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "SDBM_File"
"Safe" "Scalar::Util" "Search::Dict" "SelectSaver" "SelfLoader" "Socket"
"Storable" "Sub::Util" "Symbol" "Sys::Hostname" "TAP::Base"
"TAP::Formatter::Base" "TAP::Formatter::Color" "TAP::Formatter::Console"
"TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Harness::Beyond" "TAP::Harness::Env" "TAP::Object" "TAP::Parser"
"TAP::Parser::Aggregator" "TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::SourceHandler"
"TAP::Parser::SourceHandler::Executable" "TAP::Parser::SourceHandler::File"
"TAP::Parser::SourceHandler::Handle" "TAP::Parser::SourceHandler::Perl"
"TAP::Parser::SourceHandler::RawTAP" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer"
"Task::Weaken" "Term::ANSIColor" "Term::Cap" "Term::Complete"
"Term::ReadKey" "Term::ReadLine" "Test" "Test2" "Test2::API"
"Test2::API::Breakage" "Test2::API::Context" "Test2::API::Instance"
"Test2::API::Stack" "Test2::Event" "Test2::Event::Bail"
"Test2::Event::Diag" "Test2::Event::Exception" "Test2::Event::Generic"
"Test2::Event::Info" "Test2::Event::Note" "Test2::Event::Ok"
"Test2::Event::Plan" "Test2::Event::Skip" "Test2::Event::Subtest"
"Test2::Event::Waiting" "Test2::Formatter" "Test2::Formatter::TAP"
"Test2::Hub" "Test2::Hub::Interceptor"
"Test2::Hub::Interceptor::Terminator" "Test2::Hub::Subtest" "Test2::IPC"
"Test2::IPC::Driver" "Test2::IPC::Driver::Files" "Test2::Transition"
"Test2::Util" "Test2::Util::ExternalMeta" "Test2::Util::HashBase"
"Test2::Util::Trace" "Test::Builder" "Test::Builder::Formatter"
"Test::Builder::IO::Scalar" "Test::Builder::Module" "Test::Builder::Tester"
"Test::Builder::Tester::Color" "Test::Builder::TodoDiag" "Test::Fatal"
"Test::HACKING" "Test::Harness" "Test::LeakTrace" "Test::LeakTrace::JA"
"Test::LeakTrace::Script" "Test::More" "Test::NoWarnings"
"Test::NoWarnings::Warning" "Test::Object" "Test::Object::Test"
"Test::Requires" "Test::Simple" "Test::SubCalls" "Test::Tester"
"Test::Tester::Capture" "Test::Tester::CaptureRunner"
"Test::Tester::Delegate" "Test::Tutorial" "Test::Warnings" "Test::use::ok"
"Text::Abbrev" "Text::Balanced" "Text::Diff" "Text::Diff::Config"
"Text::Diff::Table" "Text::ParseWords" "Text::Tabs" "Text::Wrap" "Thread"
"Thread::Queue" "Thread::Semaphore" "Tie::Array" "Tie::File" "Tie::Handle"
"Tie::Hash" "Tie::Hash::NamedCapture" "Tie::Memoize" "Tie::RefHash"
"Tie::Scalar" "Tie::StdHandle" "Tie::SubstrHash" "Time::HiRes"
"Time::Local" "Time::Piece" "Time::Seconds" "Time::Zone" "Time::gmtime"
"Time::localtime" "Time::tm" "Try::Tiny" "UNIVERSAL" "URI" "URI::Escape"
"URI::Heuristic" "URI::IRI" "URI::QueryParam" "URI::Split" "URI::URL"
"URI::WithBase" "URI::_foreign" "URI::_generic" "URI::_idna" "URI::_ldap"
"URI::_login" "URI::_punycode" "URI::_query" "URI::_segment" "URI::_server"
"URI::_userpass" "URI::data" "URI::file" "URI::file::Base" "URI::file::FAT"
"URI::file::Mac" "URI::file::OS2" "URI::file::QNX" "URI::file::Unix"
"URI::file::Win32" "URI::ftp" "URI::gopher" "URI::http" "URI::https"
"URI::ldap" "URI::ldapi" "URI::ldaps" "URI::mailto" "URI::mms" "URI::news"
"URI::nntp" "URI::pop" "URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu"
"URI::sip" "URI::sips" "URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270"
"URI::urn" "URI::urn::isbn" "URI::urn::oid" "Unicode::Collate"
"Unicode::Collate::CJK::Big5" "Unicode::Collate::CJK::GB2312"
"Unicode::Collate::CJK::JISX0208" "Unicode::Collate::CJK::Korean"
"Unicode::Collate::CJK::Pinyin" "Unicode::Collate::CJK::Stroke"
"Unicode::Collate::Locale" "Unicode::Normalize" "Unicode::UCD"
"User::grent" "User::pwent" "WWW::RobotRules"
"WWW::RobotRules::AnyDBM_File" "XML::Parser" "XML::Parser::Expat"
"XML::Parser::Style::Debug" "XML::Parser::Style::Objects"
"XML::Parser::Style::Stream" "XML::Parser::Style::Subs"
"XML::Parser::Style::Tree" "XSLoader" "YAML" "YAML::Any" "YAML::Dumper"
"YAML::Dumper::Base" "YAML::Error" "YAML::Loader" "YAML::Loader::Base"
"YAML::Marshall" "YAML::Mo" "YAML::Node" "YAML::Tag" "YAML::Tiny"
"YAML::Types" "_charnames" "a2p" "arybase" "attributes" "autouse" "base"
"bigint" "bignum" "bigrat" "blib" "bytes" "charnames" "constant" "cpanfile"
"cpanfile-faq" "deprecate" "diagnostics" "encoding" "encoding::warnings"
"feature" "fields" "filetest" "if" "inc::latest" "inc::latest::private"
"integer" "less" "lib" "lib::core::only" "local::lib" "locale" "lwpcook"
"lwptut" "mro" "ok" "open.pod" "ops" "overload" "overload::numbers"
"overloading" "parent" "perl" "perl5004delta" "perl5005delta"
"perl5100delta" "perl5101delta" "perl5120delta" "perl5121delta"
"perl5122delta" "perl5123delta" "perl5124delta" "perl5140delta"
"perl5141delta" "perl5142delta" "perl5143delta" "perl5160delta"
"perl5161delta" "perl5162delta" "perl5163delta" "perl561delta"
"perl56delta" "perl581delta" "perl582delta" "perl583delta" "perl584delta"
"perl585delta" "perl586delta" "perl587delta" "perl588delta" "perl589delta"
"perl58delta" "perlaix" "perlamiga" "perlapi" "perlapio" "perlartistic"
"perlbeos" "perlbook" "perlboot" "perlbot" "perlbs2000" "perlcall" "perlce"
"perlcheat" "perlclib" "perlcn" "perlcommunity" "perlcygwin" "perldata"
"perldbmfilter" "perldebguts" "perldebtut" "perldebug" "perldelta"
"perldgux" "perldiag" "perldoc" "perldos" "perldsc" "perldtrace"
"perlebcdic" "perlembed" "perlepoc" "perlexperiment" "perlfaq" "perlfaq1"
"perlfaq2" "perlfaq3" "perlfaq4" "perlfaq5" "perlfaq6" "perlfaq7"
"perlfaq8" "perlfaq9" "perlfork" "perlform" "perlfreebsd" "perlfunc"
"perlgit" "perlglossary" "perlgpl" "perlguts" "perlhack" "perlhacktips"
"perlhacktut" "perlhaiku" "perlhist" "perlhpux" "perlhurd" "perlintern"
"perlinterp" "perlintro" "perliol" "perlipc" "perlirix" "perljp" "perlko"
"perllexwarn" "perllinux" "perllocal" "perllocale" "perllol" "perlmacos"
"perlmacosx" "perlmod" "perlmodinstall" "perlmodlib" "perlmodstyle"
"perlmpeix" "perlmroapi" "perlnetware" "perlnewmod" "perlnumber" "perlobj"
"perlootut" "perlop" "perlopenbsd" "perlopentut" "perlos2" "perlos390"
"perlos400" "perlpacktut" "perlperf" "perlplan9" "perlpod" "perlpodspec"
"perlpolicy" "perlport" "perlpragma" "perlqnx" "perlre" "perlreapi"
"perlrebackslash" "perlrecharclass" "perlref" "perlreftut" "perlreguts"
"perlrequick" "perlreref" "perlretut" "perlriscos" "perlrun" "perlsec"
"perlsolaris" "perlsource" "perlstyle" "perlsub" "perlsymbian" "perlsyn"
"perlthrtut" "perltie" "perltoc" "perltodo" "perltooc" "perltoot"
"perltrap" "perltru64" "perltw" "perlunicode" "perlunifaq" "perluniintro"
"perluniprops" "perlunitut" "perlutil" "perluts" "perlvar" "perlvmesa"
"perlvms" "perlvos" "perlwin32" "perlxs" "perlxstut" "perlxstypemap" "re"
"sigtrap" "sort.pod" "strict" "subs" "threads" "threads::shared"
"unicore::Name" "utf8" "vars" "vendor_perl::Algorithm::Diff"
"vendor_perl::Algorithm::DiffOld" "vendor_perl::App::Prove"
"vendor_perl::App::Prove::State" "vendor_perl::App::Prove::State::Result"
"vendor_perl::App::Prove::State::Result::Test"
"vendor_perl::App::cpanminus" "vendor_perl::Archive::Zip"
"vendor_perl::Archive::Zip::Archive"
"vendor_perl::Archive::Zip::BufferedFileHandle"
"vendor_perl::Archive::Zip::DirectoryMember"
"vendor_perl::Archive::Zip::FAQ" "vendor_perl::Archive::Zip::FileMember"
"vendor_perl::Archive::Zip::Member" "vendor_perl::Archive::Zip::MemberRead"
"vendor_perl::Archive::Zip::MockFileHandle"
"vendor_perl::Archive::Zip::NewFileMember"
"vendor_perl::Archive::Zip::StringMember" "vendor_perl::Archive::Zip::Tree"
"vendor_perl::Archive::Zip::ZipFileMember" "vendor_perl::Business::ISBN"
"vendor_perl::Business::ISBN10" "vendor_perl::Business::ISBN13"
"vendor_perl::Business::ISBN::Data" "vendor_perl::CPAN::Meta"
"vendor_perl::CPAN::Meta::Converter" "vendor_perl::CPAN::Meta::Feature"
"vendor_perl::CPAN::Meta::History" "vendor_perl::CPAN::Meta::Prereqs"
"vendor_perl::CPAN::Meta::Requirements" "vendor_perl::CPAN::Meta::Spec"
"vendor_perl::CPAN::Meta::Validator" "vendor_perl::CPAN::Meta::YAML"
"vendor_perl::Carp" "vendor_perl::Carp::Heavy"
"vendor_perl::Compress::Raw::Bzip2" "vendor_perl::Compress::Raw::Zlib"
"vendor_perl::Cwd" "vendor_perl::Data::Dumper" "vendor_perl::Date::Format"
"vendor_perl::Date::Language" "vendor_perl::Date::Language::Afar"
"vendor_perl::Date::Language::Amharic"
"vendor_perl::Date::Language::Austrian"
"vendor_perl::Date::Language::Brazilian"
"vendor_perl::Date::Language::Bulgarian"
"vendor_perl::Date::Language::Chinese"
"vendor_perl::Date::Language::Chinese_GB"
"vendor_perl::Date::Language::Czech" "vendor_perl::Date::Language::Danish"
"vendor_perl::Date::Language::Dutch" "vendor_perl::Date::Language::English"
"vendor_perl::Date::Language::Finnish"
"vendor_perl::Date::Language::French" "vendor_perl::Date::Language::Gedeo"
"vendor_perl::Date::Language::German" "vendor_perl::Date::Language::Greek"
"vendor_perl::Date::Language::Hungarian"
"vendor_perl::Date::Language::Icelandic"
"vendor_perl::Date::Language::Italian"
"vendor_perl::Date::Language::Norwegian"
"vendor_perl::Date::Language::Oromo"
"vendor_perl::Date::Language::Romanian"
"vendor_perl::Date::Language::Russian"
"vendor_perl::Date::Language::Russian_cp1251"
"vendor_perl::Date::Language::Russian_koi8r"
"vendor_perl::Date::Language::Sidama" "vendor_perl::Date::Language::Somali"
"vendor_perl::Date::Language::Spanish"
"vendor_perl::Date::Language::Swedish"
"vendor_perl::Date::Language::Tigrinya"
"vendor_perl::Date::Language::TigrinyaEritrean"
"vendor_perl::Date::Language::TigrinyaEthiopian"
"vendor_perl::Date::Language::Turkish" "vendor_perl::Date::Parse"
"vendor_perl::Digest" "vendor_perl::Digest::MD5" "vendor_perl::Digest::SHA"
"vendor_perl::Digest::SHA1" "vendor_perl::Digest::base"
"vendor_perl::Digest::file" "vendor_perl::Encode"
"vendor_perl::Encode::Alias" "vendor_perl::Encode::Byte"
"vendor_perl::Encode::CJKConstants" "vendor_perl::Encode::CN"
"vendor_perl::Encode::CN::HZ" "vendor_perl::Encode::Config"
"vendor_perl::Encode::EBCDIC" "vendor_perl::Encode::Encoder"
"vendor_perl::Encode::Encoding" "vendor_perl::Encode::GSM0338"
"vendor_perl::Encode::Guess" "vendor_perl::Encode::JP"
"vendor_perl::Encode::JP::H2Z" "vendor_perl::Encode::JP::JIS7"
"vendor_perl::Encode::KR" "vendor_perl::Encode::KR::2022_KR"
"vendor_perl::Encode::Locale" "vendor_perl::Encode::MIME::Header"
"vendor_perl::Encode::MIME::Header::ISO_2022_JP"
"vendor_perl::Encode::MIME::Name" "vendor_perl::Encode::PerlIO"
"vendor_perl::Encode::Supported" "vendor_perl::Encode::Symbol"
"vendor_perl::Encode::TW" "vendor_perl::Encode::Unicode"
"vendor_perl::Encode::Unicode::UTF7" "vendor_perl::Error"
"vendor_perl::Error::Simple" "vendor_perl::Exporter"
"vendor_perl::Exporter::Heavy" "vendor_perl::ExtUtils::Command::MM"
"vendor_perl::ExtUtils::Liblist" "vendor_perl::ExtUtils::Liblist::Kid"
"vendor_perl::ExtUtils::MM" "vendor_perl::ExtUtils::MM_AIX"
"vendor_perl::ExtUtils::MM_Any" "vendor_perl::ExtUtils::MM_BeOS"
"vendor_perl::ExtUtils::MM_Cygwin" "vendor_perl::ExtUtils::MM_DOS"
"vendor_perl::ExtUtils::MM_Darwin" "vendor_perl::ExtUtils::MM_MacOS"
"vendor_perl::ExtUtils::MM_NW5" "vendor_perl::ExtUtils::MM_OS2"
"vendor_perl::ExtUtils::MM_QNX" "vendor_perl::ExtUtils::MM_UWIN"
"vendor_perl::ExtUtils::MM_Unix" "vendor_perl::ExtUtils::MM_VMS"
"vendor_perl::ExtUtils::MM_VOS" "vendor_perl::ExtUtils::MM_Win32"
"vendor_perl::ExtUtils::MM_Win95" "vendor_perl::ExtUtils::MY"
"vendor_perl::ExtUtils::MakeMaker"
"vendor_perl::ExtUtils::MakeMaker::Config"
"vendor_perl::ExtUtils::MakeMaker::FAQ"
"vendor_perl::ExtUtils::MakeMaker::Tutorial"
"vendor_perl::ExtUtils::Manifest" "vendor_perl::ExtUtils::Mkbootstrap"
"vendor_perl::ExtUtils::Mksymlists" "vendor_perl::ExtUtils::ParseXS"
"vendor_perl::ExtUtils::ParseXS::Constants"
"vendor_perl::ExtUtils::ParseXS::CountLines"
"vendor_perl::ExtUtils::ParseXS::Utilities"
"vendor_perl::ExtUtils::Typemaps" "vendor_perl::ExtUtils::Typemaps::Cmd"
"vendor_perl::ExtUtils::Typemaps::InputMap"
"vendor_perl::ExtUtils::Typemaps::OutputMap"
"vendor_perl::ExtUtils::Typemaps::Type" "vendor_perl::ExtUtils::testlib"
"vendor_perl::File::Listing" "vendor_perl::File::Path"
"vendor_perl::File::Spec" "vendor_perl::File::Spec::Cygwin"
"vendor_perl::File::Spec::Epoc" "vendor_perl::File::Spec::Functions"
"vendor_perl::File::Spec::Mac" "vendor_perl::File::Spec::OS2"
"vendor_perl::File::Spec::Unix" "vendor_perl::File::Spec::Win32"
"vendor_perl::File::Temp" "vendor_perl::Filter::Util::Call"
"vendor_perl::Filter::Util::Exec" "vendor_perl::Filter::Util::perlfilter"
"vendor_perl::Filter::cpp" "vendor_perl::Filter::decrypt"
"vendor_perl::Filter::exec" "vendor_perl::Filter::sh"
"vendor_perl::Filter::tee" "vendor_perl::Getopt::Long" "vendor_perl::Git"
"vendor_perl::Git::I18N" "vendor_perl::Git::IndexInfo"
"vendor_perl::HTML::Entities" "vendor_perl::HTML::Filter"
"vendor_perl::HTML::HeadParser" "vendor_perl::HTML::LinkExtor"
"vendor_perl::HTML::Parser" "vendor_perl::HTML::PullParser"
"vendor_perl::HTML::Tagset" "vendor_perl::HTML::TokeParser"
"vendor_perl::HTTP::Config" "vendor_perl::HTTP::Cookies"
"vendor_perl::HTTP::Cookies::Microsoft"
"vendor_perl::HTTP::Cookies::Netscape" "vendor_perl::HTTP::Daemon"
"vendor_perl::HTTP::Date" "vendor_perl::HTTP::Headers"
"vendor_perl::HTTP::Headers::Auth" "vendor_perl::HTTP::Headers::ETag"
"vendor_perl::HTTP::Headers::Util" "vendor_perl::HTTP::Message"
"vendor_perl::HTTP::Negotiate" "vendor_perl::HTTP::Request"
"vendor_perl::HTTP::Request::Common" "vendor_perl::HTTP::Response"
"vendor_perl::HTTP::Status" "vendor_perl::HTTP::Tiny"
"vendor_perl::IO::HTML" "vendor_perl::IO::Socket::IP"
"vendor_perl::IO::Socket::SSL" "vendor_perl::IO::Socket::SSL::Intercept"
"vendor_perl::IO::Socket::SSL::Utils" "vendor_perl::IPC::Cmd"
"vendor_perl::JSON::PP" "vendor_perl::JSON::PP::Boolean"
"vendor_perl::LWP::MediaTypes" "vendor_perl::List::Util"
"vendor_perl::List::Util::XS" "vendor_perl::Locale::Maketext"
"vendor_perl::Locale::Maketext::Cookbook"
"vendor_perl::Locale::Maketext::Guts"
"vendor_perl::Locale::Maketext::GutsLoader"
"vendor_perl::Locale::Maketext::TPJ13" "vendor_perl::Module::Build"
"vendor_perl::Module::Build::API" "vendor_perl::Module::Build::Authoring"
"vendor_perl::Module::Build::Base" "vendor_perl::Module::Build::Bundling"
"vendor_perl::Module::Build::Compat" "vendor_perl::Module::Build::Config"
"vendor_perl::Module::Build::ConfigData"
"vendor_perl::Module::Build::Cookbook" "vendor_perl::Module::Build::Dumper"
"vendor_perl::Module::Build::ModuleInfo"
"vendor_perl::Module::Build::Notes" "vendor_perl::Module::Build::PPMMaker"
"vendor_perl::Module::Build::Platform::Amiga"
"vendor_perl::Module::Build::Platform::Default"
"vendor_perl::Module::Build::Platform::EBCDIC"
"vendor_perl::Module::Build::Platform::MPEiX"
"vendor_perl::Module::Build::Platform::MacOS"
"vendor_perl::Module::Build::Platform::RiscOS"
"vendor_perl::Module::Build::Platform::Unix"
"vendor_perl::Module::Build::Platform::VMS"
"vendor_perl::Module::Build::Platform::VOS"
"vendor_perl::Module::Build::Platform::Windows"
"vendor_perl::Module::Build::Platform::aix"
"vendor_perl::Module::Build::Platform::cygwin"
"vendor_perl::Module::Build::Platform::darwin"
"vendor_perl::Module::Build::Platform::os2"
"vendor_perl::Module::Build::PodParser"
"vendor_perl::Module::Build::Version" "vendor_perl::Module::Build::YAML"
"vendor_perl::Module::Load" "vendor_perl::Module::Load::Conditional"
"vendor_perl::Module::Metadata" "vendor_perl::Module::Signature"
"vendor_perl::Net::HTTP" "vendor_perl::Net::HTTP::Methods"
"vendor_perl::Net::HTTP::NB" "vendor_perl::Net::HTTPS"
"vendor_perl::Net::LibIDN" "vendor_perl::Net::SSLeay"
"vendor_perl::Net::SSLeay::Handle" "vendor_perl::PAR::Dist"
"vendor_perl::POD2::DE::local::lib" "vendor_perl::POD2::PT_BR::local::lib"
"vendor_perl::Params::Check" "vendor_perl::Parse::CPAN::Meta"
"vendor_perl::Perl::OSType" "vendor_perl::Pod::Man"
"vendor_perl::Pod::ParseLink" "vendor_perl::Pod::Perldoc"
"vendor_perl::Pod::Perldoc::BaseTo" "vendor_perl::Pod::Perldoc::GetOptsOO"
"vendor_perl::Pod::Perldoc::ToANSI" "vendor_perl::Pod::Perldoc::ToChecker"
"vendor_perl::Pod::Perldoc::ToMan" "vendor_perl::Pod::Perldoc::ToNroff"
"vendor_perl::Pod::Perldoc::ToPod" "vendor_perl::Pod::Perldoc::ToRtf"
"vendor_perl::Pod::Perldoc::ToTerm" "vendor_perl::Pod::Perldoc::ToText"
"vendor_perl::Pod::Perldoc::ToTk" "vendor_perl::Pod::Perldoc::ToXml"
"vendor_perl::Pod::Simple" "vendor_perl::Pod::Simple::BlackBox"
"vendor_perl::Pod::Simple::Checker" "vendor_perl::Pod::Simple::Debug"
"vendor_perl::Pod::Simple::DumpAsText"
"vendor_perl::Pod::Simple::DumpAsXML" "vendor_perl::Pod::Simple::HTML"
"vendor_perl::Pod::Simple::HTMLBatch"
"vendor_perl::Pod::Simple::HTMLLegacy"
"vendor_perl::Pod::Simple::LinkSection" "vendor_perl::Pod::Simple::Methody"
"vendor_perl::Pod::Simple::Progress" "vendor_perl::Pod::Simple::PullParser"
"vendor_perl::Pod::Simple::PullParserEndToken"
"vendor_perl::Pod::Simple::PullParserStartToken"
"vendor_perl::Pod::Simple::PullParserTextToken"
"vendor_perl::Pod::Simple::PullParserToken" "vendor_perl::Pod::Simple::RTF"
"vendor_perl::Pod::Simple::Search" "vendor_perl::Pod::Simple::SimpleTree"
"vendor_perl::Pod::Simple::Subclassing" "vendor_perl::Pod::Simple::Text"
"vendor_perl::Pod::Simple::TextContent"
"vendor_perl::Pod::Simple::TiedOutFH" "vendor_perl::Pod::Simple::Transcode"
"vendor_perl::Pod::Simple::TranscodeDumb"
"vendor_perl::Pod::Simple::TranscodeSmart"
"vendor_perl::Pod::Simple::XHTML" "vendor_perl::Pod::Simple::XMLOutStream"
"vendor_perl::Pod::Text" "vendor_perl::Pod::Text::Color"
"vendor_perl::Pod::Text::Overstrike" "vendor_perl::Pod::Text::Termcap"
"vendor_perl::Pod::Usage" "vendor_perl::Scalar::Util" "vendor_perl::Socket"
"vendor_perl::Storable" "vendor_perl::TAP::Base"
"vendor_perl::TAP::Formatter::Base" "vendor_perl::TAP::Formatter::Color"
"vendor_perl::TAP::Formatter::Console"
"vendor_perl::TAP::Formatter::Console::ParallelSession"
"vendor_perl::TAP::Formatter::Console::Session"
"vendor_perl::TAP::Formatter::File"
"vendor_perl::TAP::Formatter::File::Session"
"vendor_perl::TAP::Formatter::Session" "vendor_perl::TAP::Harness"
"vendor_perl::TAP::Harness::Beyond" "vendor_perl::TAP::Object"
"vendor_perl::TAP::Parser" "vendor_perl::TAP::Parser::Aggregator"
"vendor_perl::TAP::Parser::Grammar" "vendor_perl::TAP::Parser::Iterator"
"vendor_perl::TAP::Parser::Iterator::Array"
"vendor_perl::TAP::Parser::Iterator::Process"
"vendor_perl::TAP::Parser::Iterator::Stream"
"vendor_perl::TAP::Parser::IteratorFactory"
"vendor_perl::TAP::Parser::Multiplexer" "vendor_perl::TAP::Parser::Result"
"vendor_perl::TAP::Parser::Result::Bailout"
"vendor_perl::TAP::Parser::Result::Comment"
"vendor_perl::TAP::Parser::Result::Plan"
"vendor_perl::TAP::Parser::Result::Pragma"
"vendor_perl::TAP::Parser::Result::Test"
"vendor_perl::TAP::Parser::Result::Unknown"
"vendor_perl::TAP::Parser::Result::Version"
"vendor_perl::TAP::Parser::Result::YAML"
"vendor_perl::TAP::Parser::ResultFactory"
"vendor_perl::TAP::Parser::Scheduler"
"vendor_perl::TAP::Parser::Scheduler::Job"
"vendor_perl::TAP::Parser::Scheduler::Spinner"
"vendor_perl::TAP::Parser::Source"
"vendor_perl::TAP::Parser::SourceHandler"
"vendor_perl::TAP::Parser::SourceHandler::Executable"
"vendor_perl::TAP::Parser::SourceHandler::File"
"vendor_perl::TAP::Parser::SourceHandler::Handle"
"vendor_perl::TAP::Parser::SourceHandler::Perl"
"vendor_perl::TAP::Parser::SourceHandler::RawTAP"
"vendor_perl::TAP::Parser::Utils"
"vendor_perl::TAP::Parser::YAMLish::Reader"
"vendor_perl::TAP::Parser::YAMLish::Writer" "vendor_perl::Term::ReadKey"
"vendor_perl::Test::HACKING" "vendor_perl::Test::Harness"
"vendor_perl::Text::Diff" "vendor_perl::Text::Diff::Config"
"vendor_perl::Text::Diff::Table" "vendor_perl::Text::ParseWords"
"vendor_perl::Thread::Queue" "vendor_perl::Time::HiRes"
"vendor_perl::Time::Local" "vendor_perl::Time::Zone"
"vendor_perl::WWW::RobotRules" "vendor_perl::WWW::RobotRules::AnyDBM_File"
"vendor_perl::XML::Parser" "vendor_perl::XML::Parser::Expat"
"vendor_perl::XML::Parser::Style::Debug"
"vendor_perl::XML::Parser::Style::Objects"
"vendor_perl::XML::Parser::Style::Stream"
"vendor_perl::XML::Parser::Style::Subs"
"vendor_perl::XML::Parser::Style::Tree" "vendor_perl::YAML"
"vendor_perl::YAML::Any" "vendor_perl::YAML::Dumper"
"vendor_perl::YAML::Dumper::Base" "vendor_perl::YAML::Error"
"vendor_perl::YAML::Loader" "vendor_perl::YAML::Loader::Base"
"vendor_perl::YAML::Marshall" "vendor_perl::YAML::Mo"
"vendor_perl::YAML::Node" "vendor_perl::YAML::Tag"
"vendor_perl::YAML::Tiny" "vendor_perl::YAML::Types"
"vendor_perl::constant" "vendor_perl::encoding" "vendor_perl::inc::latest"
"vendor_perl::inc::latest::private" "vendor_perl::lib::core::only"
"vendor_perl::local::lib" "vendor_perl::parent" "vendor_perl::perldoc"
"vendor_perl::threads" "vendor_perl::threads::shared"
"vendor_perl::version" "vendor_perl::version::Internals"
"vendor_perl::version::regex" "vendor_perl::version::vpp"
"vendor_perl::version::vxs" "version" "version::Internals" "version::regex"
"version::vpp" "version::vxs" "vmsish" "warnings" "warnings::register"))
